const U='https://www.groupe-ntb.com/wp-content/uploads/';
const NTB={name:'NTB — New Tools Bey',short:'NTB',tagline:'We make the difference',phone:'0561 61 16 84',tel:'tel:0561611684',wa:'https://wa.me/213561611684',email:'ntb.commercial@gmail.com',addr:'El Hamiz, Alger 16033',map:'https://www.google.com/maps/search/?api=1&query=El+Hamiz+Alger',fb:'https://www.facebook.com/',ig:'https://www.instagram.com/ntbtools/',logo:U+'2022/04/cropped-1-NTB-Logo-LARGEf.png',
 banners:[U+'2024/09/Website-slider-ECO-Serie.jpg',U+'2022/05/Slide-NTB-scaled-1500x600.jpg',U+'2022/05/meche-scaled-1500x600.jpg',U+'2022/05/Pub-ORCA-3-e1652273567368-1144x457.jpg']};
const CATS=[
 {id:'powertools',n:'Outillage électrique',c:272,img:U+'2022/05/NTB-categories-orca-324x324.jpg',d:'Perforateurs, visseuses, postes à souder, aspirateurs.'},
 {id:'quincaillerie',n:'Quincaillerie',c:316,img:U+'2022/05/NTB-categories-Quincaillerie-2-324x324.jpg',d:'Fixation, serrurerie, visserie et accessoires.'},
 {id:'disques',n:'Disques & mèches',c:360,img:U+'2022/05/NTB-categories-disque-et-meches-324x324.jpg',d:'Disques à tronçonner, à meuler, mèches béton et métal.'},
 {id:'peinture',n:'Peinture',c:130,img:U+'2022/05/NTB-categories-peinture-V-324x324.jpg',d:'Aérosols BEY, colles, anti-gravillons, anti-rouille.'},
 {id:'mecanique',n:'Mécanique',c:161,img:U+'2022/05/NTB-categories-mecanique-324x324.jpg',d:'Clés, douilles, chargeurs et outillage atelier.'},
 {id:'securite',n:'Sécurité',c:75,img:U+'2022/05/NTB-categories-securite-324x324.jpg',d:'Casques, masques de soudure, protection individuelle.'},
 {id:'maconnerie',n:'Maçonnerie',c:21,img:U+'2022/05/NTB-categories-maconnerie-324x324.jpg',d:'Truelles, niveaux, outils du bâtiment.'},
 {id:'jardinage',n:'Jardinage',c:32,img:U+'2022/05/NTB-categories-jardinage-2-324x324.jpg',d:'Outils et accessoires pour l\'entretien des espaces verts.'},
 {id:'autre',n:'Autres références',c:1439,img:U+'2022/05/NTB-categories-autre-324x324.jpg',d:'Plus de 1 400 références complémentaires.'}];
const TOTAL_REF=CATS.reduce((s,c)=>s+c.c,0);
const BRANDS=['ORCA','BEY','BEETRO','CAPRO','FIDEA','DARFIX','SOMAFIX'];
// prix = indicatifs pour la maquette
const PRODUCTS=[
 {id:'erh020',n:'Marteau perforateur 20V à batterie 26 mm — ERH020',b:'ORCA',cat:'powertools',sku:'ERH020',p:24900,img:U+'2025/04/ERH020-1-324x324.jpg',big:U+'2025/04/ERH020-1.jpg',tag:'Nouveau',
  d:'Perforateur sans fil 20V pour le perçage et le burinage léger dans le béton, la brique et le métal. Mandrin SDS, batterie lithium 4.0 Ah, idéal pour les chantiers sans prise électrique.',
  sp:[['Tension','20 V'],['Capacité de perçage béton','26 mm'],['Batterie','Li-ion 4.0 Ah'],['Modes','Perçage, perforation, burinage'],['Emmanchement','SDS-Plus'],['Garantie','Selon conditions NTB']],
  hi:['Sans fil, 20V','Béton jusqu\'à 26 mm','Batterie 4.0 Ah'],use:['Choisir le mode (perçage, perforation ou burinage) selon le matériau.','Insérer le foret SDS jusqu\'au verrouillage.','Percer perpendiculairement, sans forcer : laisser l\'outil travailler.']},
 {id:'vbc600',n:'Chargeur démarreur 600A — VBC600',b:'ORCA',cat:'mecanique',sku:'r22c0002',p:38500,img:U+'2025/05/CHARGEUR-DEMARREUR-600A-VBC600-ORCA-416x416.jpg',big:U+'2025/05/CHARGEUR-DEMARREUR-600A-VBC600-ORCA.jpg',tag:'Best-seller',
  d:'Chargeur de batterie et aide au démarrage pour véhicules légers et utilitaires. Pensé pour les garages, ateliers et flottes.',
  sp:[['Courant de démarrage','600 A'],['Usage','Charge et démarrage'],['Batteries','12 V / 24 V (à confirmer)'],['Mobilité','Chariot à roues'],['Référence','VBC600']],
  hi:['Démarrage 600 A','Charge + boost','Usage atelier'],use:['Vérifier la tension de la batterie avant branchement.','Brancher la pince rouge sur (+) puis la noire sur (−).','Sélectionner le mode charge ou démarrage.']},
 {id:'bey315',n:'Aérosol anti-chaleur beige G315 — BEY',b:'BEY',cat:'peinture',sku:'r19j0004',p:650,img:U+'2022/04/Bey-315d-416x416.jpg',big:U+'2022/04/Bey-315d-scaled-e1650966055320.jpg',
  d:'Peinture aérosol résistante à la chaleur pour pièces exposées : poêles, barbecues, pots d\'échappement, moteurs.',
  sp:[['Teinte','Beige G315'],['Type','Anti-chaleur'],['Conditionnement','Aérosol'],['Supports','Métal'],['Marque','BEY']],
  hi:['Résiste à la chaleur','Séchage rapide','Finition uniforme'],use:['Agiter 1 minute après le cliquetis de la bille.','Pulvériser à 25–30 cm en couches fines.','Laisser sécher entre deux couches.'],
  vars:{label:'Teinte',o:[['Beige G315',650],['Noir anti-chaleur',650],['Aluminium',690]]}},
 {id:'beyp04',n:'Aérosol anti-rouille noir P04 — BEY',b:'BEY',cat:'peinture',sku:'P04',p:750,img:U+'2026/02/ANTI-ROUI-324x324.jpg',tag:'Nouveau',
  d:'Peinture aérosol anti-rouille qui protège et décore les surfaces métalliques en une seule application.',
  sp:[['Teinte','Noir P04'],['Type','Anti-rouille'],['Conditionnement','Aérosol'],['Supports','Métal ferreux'],['Marque','BEY']],
  hi:['Anti-rouille','2 en 1 : protège et colore','Métal'],use:['Dégraisser et poncer légèrement la surface.','Agiter puis pulvériser à 25–30 cm.','Appliquer 2 couches fines.']},
 {id:'bey1004',n:'Aérosol bleu fleurissant 1004 — BEY',b:'BEY',cat:'peinture',sku:'1004',p:650,img:U+'2026/02/BEY-1004-324x324.jpg',
  d:'Peinture aérosol décorative, teinte bleu fleurissant, pour bois, métal et plastiques préparés.',
  sp:[['Teinte','Bleu fleurissant 1004'],['Conditionnement','Aérosol'],['Supports','Bois, métal, plastique préparé'],['Marque','BEY']],
  hi:['Couleur vive','Multi-supports','Séchage rapide'],use:['Agiter 1 minute.','Pulvériser à 25–30 cm.','Laisser sécher entre les couches.']},
 {id:'colle-bois',n:'Colle à bois vinylique — BEY',b:'BEY',cat:'peinture',sku:'CB-BEY',p:390,img:null,
  d:'Colle blanche vinylique pour l\'assemblage des bois, panneaux et placages. Du flacon de 60 g au seau de 3 kg pour les ateliers de menuiserie.',
  sp:[['Type','Vinylique'],['Supports','Bois, agglo, contreplaqué'],['Formats','60 g à 3 kg'],['Marque','BEY']],
  hi:['6 formats','Ateliers & particuliers','Prise solide'],use:['Appliquer sur des surfaces propres et sèches.','Presser les pièces et essuyer l\'excédent.','Maintenir sous serrage le temps de la prise.'],
  vars:{label:'Format',o:[['60 g',180],['185 g',290],['300 g',390],['500 g',620],['800 g',950],['3 kg',2900]]}},
 {id:'fidea800',n:'Anti-gravillon noir 800 ml — FIDEA',b:'FIDEA',cat:'peinture',sku:'FID800',p:1150,img:null,
  d:'Revêtement de protection anti-gravillon pour bas de caisse et passages de roue.',
  sp:[['Teinte','Noir'],['Contenance','800 ml'],['Usage','Carrosserie'],['Marque','FIDEA']],
  hi:['Protège la carrosserie','800 ml','Finition texturée'],use:['Masquer les zones à protéger.','Appliquer au pistolet adapté en couches croisées.','Laisser sécher avant peinture de finition.']},
 {id:'mdf',n:'Colle MDF 100 ml — DARFIX',b:'DARFIX',cat:'peinture',sku:'DAR100',p:480,img:null,
  d:'Colle rapide pour MDF et panneaux, idéale pour les finitions et petites réparations de menuiserie.',
  sp:[['Contenance','100 ml'],['Supports','MDF, bois, panneaux'],['Marque','DARFIX']],
  hi:['Prise rapide','Menuiserie','100 ml'],use:['Appliquer la colle sur une face.','Pulvériser l\'activateur si fourni sur l\'autre face.','Assembler et maintenir quelques secondes.']},
 {id:'vac1600',n:'Aspirateur 1600W — VAC-1600',b:'ORCA',cat:'powertools',sku:'VAC-1600',p:18900,img:null,
  d:'Aspirateur eau et poussière pour ateliers et chantiers, avec cuve grande capacité.',
  sp:[['Puissance','1600 W'],['Usage','Eau et poussière'],['Référence','VAC-1600']],
  hi:['1600 W','Eau & poussière','Chantier'],use:['Vérifier le filtre avant utilisation.','Choisir l\'accessoire selon la surface.','Vider la cuve après chaque usage.']},
 {id:'cd325',n:'Visseuse 12V Li-ion avec outils — CD325',b:'ORCA',cat:'powertools',sku:'CD325',p:9900,img:null,tag:'Pack',
  d:'Visseuse-perceuse compacte 12V livrée avec un jeu d\'embouts et d\'outils, pour le montage et les petits travaux.',
  sp:[['Tension','12 V'],['Batterie','Li-ion'],['Livrée avec','Jeu d\'outils'],['Référence','CD325']],
  hi:['Compacte','Pack outils inclus','12 V'],use:['Charger complètement la batterie avant la première utilisation.','Régler le couple selon le vissage.','Percer en mode perçage, visser en mode vissage.']},
 {id:'nm120',n:'Cloueuse pneumatique 50 mm — NM120',b:'ORCA',cat:'powertools',sku:'NM120',p:14500,img:null,
  d:'Cloueuse pneumatique pour pointes jusqu\'à 50 mm : menuiserie, coffrage, emballage.',
  sp:[['Longueur de pointe','Jusqu\'à 50 mm'],['Alimentation','Air comprimé'],['Référence','NM120']],
  hi:['Pointes 50 mm','Pneumatique','Menuiserie'],use:['Raccorder au compresseur à la pression recommandée.','Charger le magasin.','Toujours porter des lunettes de protection.']},
 {id:'pnm750',n:'Pistolet à peinture, jeu 5 pièces — PNM750',b:'ORCA',cat:'powertools',sku:'PNM750',p:7900,img:null,
  d:'Kit pistolet à peinture pneumatique 5 pièces pour les travaux de carrosserie et de peinture en atelier.',
  sp:[['Composition','Jeu de 5 pièces'],['Alimentation','Air comprimé'],['Référence','PNM750']],
  hi:['Kit 5 pièces','Carrosserie','Pneumatique'],use:['Filtrer la peinture avant remplissage.','Régler le jet et la pression.','Nettoyer le pistolet après usage.']},
 {id:'eco200',n:'Poste à souder ECO200',b:'ORCA',cat:'powertools',sku:'ECO200',p:21500,img:null,tag:'Série ECO',
  d:'Poste à souder à l\'arc de la série ECO, pour la soudure à l\'électrode enrobée en atelier et sur chantier.',
  sp:[['Procédé','Arc (électrode enrobée)'],['Série','ECO'],['Référence','ECO200']],
  hi:['Série ECO','Atelier & chantier','Électrode enrobée'],use:['Raccorder la pince de masse près de la zone de soudure.','Régler l\'intensité selon l\'électrode.','Toujours utiliser un masque de soudure.']},
 {id:'cap01',n:'Masque de soudure automatique — CAP01',b:'ORCA',cat:'securite',sku:'CAP01',p:6500,img:null,
  d:'Masque de soudure à teinte automatique : l\'écran s\'assombrit à l\'amorçage de l\'arc pour protéger les yeux.',
  sp:[['Filtre','Teinte automatique'],['Usage','Soudure à l\'arc'],['Référence','CAP01']],
  hi:['Auto-obscurcissant','Confort','Sécurité'],use:['Ajuster le serre-tête.','Vérifier le fonctionnement du filtre avant de souder.','Remplacer les écrans de protection usés.']},
 {id:'wh01',n:'Casque de soudure — WH01',b:'ORCA',cat:'securite',sku:'WH01',p:3900,img:null,
  d:'Casque de soudure classique, léger et robuste, pour les soudeurs occasionnels comme professionnels.',
  sp:[['Type','Casque de soudure'],['Référence','WH01']],
  hi:['Léger','Robuste','Soudure'],use:['Ajuster au tour de tête.','Vérifier l\'état du verre filtrant.']},
 {id:'pince300',n:'Câble pince électrode 300A',b:'NTB',cat:'powertools',sku:'CPE300',p:2400,img:null,
  d:'Câble équipé d\'une pince porte-électrode 300A, pour postes à souder à l\'arc.',
  sp:[['Intensité','300 A'],['Usage','Porte-électrode']],
  hi:['300 A','Accessoire soudure'],use:['Brancher sur la sortie du poste.','Vérifier l\'isolation du câble avant usage.']}
];
const byId=id=>PRODUCTS.find(p=>p.id===id);
const catOf=id=>CATS.find(c=>c.id===id);
const WILAYAS=['Adrar','Chlef','Laghouat','Oum El Bouaghi','Batna','Béjaïa','Biskra','Béchar','Blida','Bouira','Tamanrasset','Tébessa','Tlemcen','Tiaret','Tizi Ouzou','Alger','Djelfa','Jijel','Sétif','Saïda','Skikda','Sidi Bel Abbès','Annaba','Guelma','Constantine','Médéa','Mostaganem','M\'Sila','Mascara','Ouargla','Oran','El Bayadh','Illizi','Bordj Bou Arréridj','Boumerdès','El Tarf','Tindouf','Tissemsilt','El Oued','Khenchela','Souk Ahras','Tipaza','Mila','Aïn Defla','Naâma','Aïn Témouchent','Ghardaïa','Relizane','Timimoun','Bordj Badji Mokhtar','Ouled Djellal','Béni Abbès','In Salah','In Guezzam','Touggourt','Djanet','El M\'Ghair','El Meniaa'];
